In [1]:
import osmnx as ox
import geopandas as gpd

In [6]:
polygons_gdf = gpd.read_file('_data/kemerovskaya_obl.gpkg', layer = '__')
polygons_gdf

,bbox_west,bbox_south,bbox_east,bbox_north,place_id,osm_type,osm_id,lat,lon,class,type,place_rank,importance,addresstype,name,display_name,geometry
0,84.447895,52.162703,89.402644,56.835131,201088803,relation,144763,54.533578,87.342861,boundary,administrative,8,0.623334,state,Kemerovo Oblast–Kuzbass,"Kemerovo Oblast–Kuzbass, Siberian Federal Dist...","MULTIPOLYGON (((84.44789 56.04157, 84.448 56.0..."

In [7]:
if polygons_gdf.crs != 'EPSG:4326':
    polygons_gdf = ox.projection.project_gdf(polygons_gdf, to_latlong = True)

In [ ]:
SETTLEMENT_TAGS = {
    'place': ['city'],
    # 'place': ['city', 'town', 'village', 'hamlet'],
}
settlements = ox.features_from_polygon(polygons_gdf.union_all(), SETTLEMENT_TAGS)
settlements

C:\Users\obsid\AppData\Roaming\Python\Python312\site-packages\osmnx\_overpass.py:267: UserWarning: This area is 46 times your configured Overpass max query area size. It will automatically be divided up into multiple sub-queries accordingly. This may take a long time.
  multi_poly_proj = utils_geo._consolidate_subdivide_geometry(poly_proj)

                                                             geometry  \
element id
node    27505477                            POINT (87.13585 53.75759)
        178926370                           POINT (85.63132 56.06507)
        187017478                           POINT (84.89855 56.15303)
        191779212                           POINT (86.74921 53.88791)
        191908717                           POINT (86.63548 54.00499)
...                                                               ...
way     1050510507  POLYGON ((87.42906 53.75022, 87.43183 53.74942...
        1240774475  POLYGON ((85.47402 55.8274, 85.47361 55.82728,...
        1242247194  POLYGON ((85.50459 54.78081, 85.50698 54.78088...
        1314646650  POLYGON ((88.32982 55.74523, 88.3357 55.74623,...
        1391509973  POLYGON ((85.75332 55.33793, 85.75351 55.33787...

                   alt_name         name    place population population:date  \
element id
node    27505477        NaN  Новокузнецк     city     533565      2023-01-01
        178926370       NaN        Тайга     town      22092      2023-01-01
        187017478       NaN       Алаево   hamlet         16      2010-10-14
        191779212       NaN  Прокопьевск     city     174859      2023-01-01
        191908717       NaN    Киселёвск     town      81887      2023-01-01
...                     ...          ...      ...        ...             ...
way     1050510507      NaN     Тальжино  village        NaN             NaN
        1240774475      NaN          NaN  village        NaN             NaN
        1242247194      NaN      Пушкино   hamlet        NaN             NaN
        1314646650      NaN       Утинка  village        441      2010-10-14
        1391509973      NaN      Дедюево   hamlet        NaN             NaN

                     wikidata                        wikipedia  \
element id
node    27505477       Q93910                   ru:Новокузнецк
        178926370     Q196592                 ru:Тайга (город)
        187017478   Q27574717  ru:Алаево (Кемеровская область)
        191779212     Q184147                   ru:Прокопьевск
        191908717     Q153663                     ru:Киселёвск
...                       ...                              ...
way     1050510507        NaN                              NaN
        1240774475        NaN                              NaN
        1242247194        NaN                              NaN
        1314646650  Q27574037              ru:Утинка (посёлок)
        1391509973        NaN                              NaN

                   gns:modify_date source  ... area residential fixme type  \
element id                                 ...
node    27505477               NaN    NaN  ...  NaN         NaN   NaN  NaN
        178926370              NaN    NaN  ...  NaN         NaN   NaN  NaN
        187017478              NaN    NaN  ...  NaN         NaN   NaN  NaN
        191779212              NaN    NaN  ...  NaN         NaN   NaN  NaN
        191908717              NaN    NaN  ...  NaN         NaN   NaN  NaN
...                            ...    ...  ...  ...         ...   ...  ...
way     1050510507             NaN    NaN  ...  NaN         NaN   NaN  NaN
        1240774475             NaN    NaN  ...  NaN         NaN   NaN  NaN
        1242247194             NaN    NaN  ...  NaN         NaN   NaN  NaN
        1314646650             NaN    NaN  ...  NaN         NaN   NaN  NaN
        1391509973             NaN    NaN  ...  NaN         NaN   NaN  NaN

                   fias:code source:geometry source:geometry:date flag okato  \
element id
node    27505477         NaN             NaN                  NaN  NaN   NaN
        178926370        NaN             NaN                  NaN  NaN   NaN
        187017478        NaN             NaN                  NaN  NaN   NaN
        191779212        NaN             NaN                  NaN  NaN   NaN
        191908717        NaN             NaN                  NaN  NaN   NaN
...                      ...             ...                  ...  ...   ...
way     1050510507       NaN             NaN                  NaN  NaN   NaN
        1240774475       NaN             NaN                  NaN  NaN   NaN
        1242247194       NaN             NaN                  NaN  NaN   NaN
        1314646650       NaN             NaN                  NaN  NaN   NaN
        1391509973       NaN             NaN                  NaN  NaN   NaN

                   oktmo
element id
node    27505477     NaN
        178926370    NaN
        187017478    NaN
        191779212    NaN
        191908717    NaN
...                  ...
way     1050510507   NaN
        1240774475   NaN
        1242247194   NaN
        1314646650   NaN
        1391509973   NaN

[2201 rows x 129 columns]

In [11]:
settlements.query('place == "city"')

                                                             geometry  \
element  id
node     27505477                           POINT (87.13585 53.75759)
         191779212                          POINT (86.74921 53.88791)
         390614421                          POINT (86.08712 55.35509)
relation 1312868    POLYGON ((85.91122 55.32317, 85.91134 55.32366...
         1437127    POLYGON ((86.95438 53.65623, 86.9461 53.65858,...
         1437127    POLYGON ((86.95438 53.65623, 86.9461 53.65858,...
         1437127    POLYGON ((86.95438 53.65623, 86.9461 53.65858,...
         1437127    POLYGON ((86.95438 53.65623, 86.9461 53.65858,...
         1735836    POLYGON ((86.61466 53.94223, 86.61338 53.94853...
         1735836    POLYGON ((86.61466 53.94223, 86.61338 53.94853...
         1735836    POLYGON ((86.61466 53.94223, 86.61338 53.94853...
         1735836    POLYGON ((86.61466 53.94223, 86.61338 53.94853...

                   alt_name         name place population population:date  \
element  id
node     27505477       NaN  Новокузнецк  city     533565      2023-01-01
         191779212      NaN  Прокопьевск  city     174859      2023-01-01
         390614421      NaN     Кемерово  city     549362      2023-01-01
relation 1312868        NaN     Кемерово  city     552546      2021-01-01
         1437127        NaN  Новокузнецк  city     544583      2021-01-01
         1437127        NaN  Новокузнецк  city     544583      2021-01-01
         1437127        NaN  Новокузнецк  city     544583      2021-01-01
         1437127        NaN  Новокузнецк  city     544583      2021-01-01
         1735836        NaN  Прокопьевск  city        NaN             NaN
         1735836        NaN  Прокопьевск  city        NaN             NaN
         1735836        NaN  Прокопьевск  city        NaN             NaN
         1735836        NaN  Прокопьевск  city        NaN             NaN

                   wikidata       wikipedia gns:modify_date  \
element  id
node     27505477    Q93910  ru:Новокузнецк             NaN
         191779212  Q184147  ru:Прокопьевск             NaN
         390614421    Q6066     ru:Кемерово             NaN
relation 1312868      Q6066     ru:Кемерово             NaN
         1437127     Q93910  ru:Новокузнецк             NaN
         1437127     Q93910  ru:Новокузнецк             NaN
         1437127     Q93910  ru:Новокузнецк             NaN
         1437127     Q93910  ru:Новокузнецк             NaN
         1735836        NaN             NaN             NaN
         1735836        NaN             NaN             NaN
         1735836        NaN             NaN             NaN
         1735836        NaN             NaN             NaN

                                                               source  ...  \
element  id                                                            ...
node     27505477                                                 NaN  ...
         191779212                                                NaN  ...
         390614421                                                NaN  ...
relation 1312868    Решение Кемеровского городского СНД от 27.09.2...  ...
         1437127                                                  NaN  ...
         1437127                                                  NaN  ...
         1437127                                                  NaN  ...
         1437127                                                  NaN  ...
         1735836                                                  NaN  ...
         1735836                                                  NaN  ...
         1735836                                                  NaN  ...
         1735836                                                  NaN  ...

                   area residential fixme          type  \
element  id
node     27505477   NaN         NaN   NaN           NaN
         191779212  NaN         NaN   NaN           NaN
         390614421  NaN         NaN   NaN           NaN
relation 1312868    NaN         NaN   NaN  multipolygon
         1437127    NaN         NaN   NaN  multipolygon
         1437127    NaN         NaN   NaN  multipolygon
         1437127    NaN         NaN   NaN  multipolygon
         1437127    NaN         NaN   NaN  multipolygon
         1735836    NaN         NaN   NaN  multipolygon
         1735836    NaN         NaN   NaN  multipolygon
         1735836    NaN         NaN   NaN  multipolygon
         1735836    NaN         NaN   NaN  multipolygon

                                               fias:code source:geometry  \
element  id
node     27505477                                    NaN             NaN
         191779212                                   NaN             NaN
         390614421                                   NaN             NaN
relation 1312868    94bb19a3-c1fa-410b-8651-ac1bf7c050cd             NaN
         1437127    b28b6f6f-1435-444e-95a6-68c499b0d27a             NaN
         1437127    b28b6f6f-1435-444e-95a6-68c499b0d27a             NaN
         1437127    b28b6f6f-1435-444e-95a6-68c499b0d27a             NaN
         1437127    b28b6f6f-1435-444e-95a6-68c499b0d27a             NaN
         1735836    2d8b9d01-1c4f-4987-8a0b-1eb5080c1f38             NaN
         1735836    2d8b9d01-1c4f-4987-8a0b-1eb5080c1f38             NaN
         1735836    2d8b9d01-1c4f-4987-8a0b-1eb5080c1f38             NaN
         1735836    2d8b9d01-1c4f-4987-8a0b-1eb5080c1f38             NaN

                   source:geometry:date flag okato oktmo
element  id
node     27505477                   NaN  NaN   NaN   NaN
         191779212                  NaN  NaN   NaN   NaN
         390614421                  NaN  NaN   NaN   NaN
relation 1312868                    NaN  NaN   NaN   NaN
         1437127                    NaN  NaN   NaN   NaN
         1437127                    NaN  NaN   NaN   NaN
         1437127                    NaN  NaN   NaN   NaN
         1437127                    NaN  NaN   NaN   NaN
         1735836                    NaN  NaN   NaN   NaN
         1735836                    NaN  NaN   NaN   NaN
         1735836                    NaN  NaN   NaN   NaN
         1735836                    NaN  NaN   NaN   NaN

[12 rows x 129 columns]

In [17]:
settlements2 = settlements.copy()
settlements2.reset_index(inplace=True)
if 'element' in settlements2.columns:
    settlements2.drop('element', axis=1, inplace=True)
if 'id' in settlements2.columns:
    settlements2.drop_duplicates('id', inplace=True)
    settlements2.set_index('id', inplace=True)  #, verify_integrity = True)
    

boundaries = settlements2[settlements2.geometry.apply(lambda x: x.geom_type).isin(['Polygon', 'MultiPolygon'])]
boundaries.query('place == "city"')

,geometry,alt_name,name,place,population,population:date,wikidata,wikipedia,gns:modify_date,source,...,area,residential,fixme,type,fias:code,source:geometry,source:geometry:date,flag,okato,oktmo
id,,,,,,,,,,,,,,,,,,,,,
1312868,"POLYGON ((85.91122 55.32317, 85.91134 55.32366...",NaN,Кемерово,city,552546,2021-01-01,Q6066,ru:Кемерово,NaN,Решение Кемеровского городского СНД от 27.09.2...,...,NaN,NaN,NaN,multipolygon,94bb19a3-c1fa-410b-8651-ac1bf7c050cd,NaN,NaN,NaN,NaN,NaN
1437127,"POLYGON ((86.95438 53.65623, 86.9461 53.65858,...",NaN,Новокузнецк,city,544583,2021-01-01,Q93910,ru:Новокузнецк,NaN,NaN,...,NaN,NaN,NaN,multipolygon,b28b6f6f-1435-444e-95a6-68c499b0d27a,NaN,NaN,NaN,NaN,NaN
1735836,"POLYGON ((86.61466 53.94223, 86.61338 53.94853...",NaN,Прокопьевск,city,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,multipolygon,2d8b9d01-1c4f-4987-8a0b-1eb5080c1f38,NaN,NaN,NaN,NaN,NaN